logging.level.org.springframework=debug

#spring.mvc.apiversion.use.path-segment=0
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.use.header=GET-PERSON-API-VERSION
#spring.mvc.apiversion.use.media-type-parameter[application/json]=version

#http://localhost:8080/actuator  - access control to monitor the entire application
management.endpoints.web.exposure.include=*

#It tells Hibernate to print all SQL queries it generates to the console/logs.
spring.jpa.show-sql=true

#it tells spring to make interact with h2 database through web browser
#spring.h2.console.enable=true

#It tells spring to connect to testdb database in h2 engine using jdbc api(using h2 drivers)
#spring.datasource.url=jdbc:h2:mem:testdb

#to make addition of queries using data.sql in test db only after table creation use this works with h2 database
#spring.jpa.defer-datasource-initialization=true

# it tells spring to connect to social media database which is running in localhost and port no 3306, with the help of jdbc api using MYSQL drivers
spring.datasource.url=jdbc:mysql://localhost:3306/social-media-database

#to acces database login with these credentials
spring.datasource.username=srinath
spring.datasource.password=1234

#it tells spring to auto configure entity -> table in MySQL
spring.jpa.hibernate.ddl-auto=update

#it tells Hibernate "hey hibernate i am using MySQL, so generate SQL that MySQL understands.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
